### ISSUE TITLE
v2.1: Site groups cannot be edited or deleted

### ISSUE THREAD

**Issue by emrikol** [Automattic/syndication#112] opened 2016-08-02 16:52 UTC
In v2.1 site groups cannot be deleted.  Neither with bulk edit or individual edits.  Either a success message or error message will display, but nothing will change.

**Comment by emgk** [comment] 2017-06-01 09:28
@emrikol are you still experiencing this issue? I have tested branch 2.1 on my local machine, I didn't face any issue while deleting or editing the site group through the bulk edit or individual edit. no error message appeared, worked fine. 

cc @philipjohn

**Comment by MattGeri** [comment] 2017-06-20 13:24
I've tried to replicate this issue in an attempt to fix it, but I also cannot reproduce the bug being experienced using the code in the `master` branch.

**Comment by philipjohn** [comment] 2017-06-27 14:48
Closing given we can't reproduce.

**Closed by philipjohn** 2017-06-27 14:48 UTC
Labels: confirmed-bug, Priority::High
